theme: jekyll-theme-slate
title: Jet Quenching Tools
description: This page is a tool on its own - a collection of useful links and information. A record of workshops aiming at bringing together theorists and experimentalists interested in jet observables in heavy-ion collisions.
